# Generated by Django 4.2.7 on 2024-01-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_member_prova'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='lastname',
        ),
        migrations.AddField(
            model_name='member',
            name='prova2',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
