# Generated by Django 4.2.7 on 2024-01-04 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_remove_member_lastname_member_prova2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='prova2',
        ),
    ]
