# Generated by Django 4.2.7 on 2024-01-11 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0004_remove_member_prova2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='prova',
        ),
    ]
