# Generated by Django 4.2.7 on 2024-01-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0005_remove_member_prova'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='prova',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
