version: "3.5"

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/atarsi/data/wordpress
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/atarsi/data/mariadb
      o: bind
      type: none

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    restart: always
    networks:
      - inception
  
  wordpress:
    container_name: wordpress
    build:
      ./requirements/wordpress
    ports:
      - "9000:9000"
    restart: always
    env_file:
      - .env
    volumes:
        - wordpress:/var/www/html
    depends_on:
        - mariadb
    networks:
      - inception

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always
    env_file:
      - .env

networks:
  inception:
  

  
