# Generated by Django 4.2.7 on 2024-03-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalMatchesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(default=-1)),
                ('winner', models.CharField(default='', max_length=8)),
                ('player1', models.CharField(default='', max_length=8)),
                ('player2', models.CharField(default='', max_length=8)),
                ('p1_score', models.PositiveSmallIntegerField(default=0)),
                ('p2_score', models.PositiveSmallIntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('tournament_game', models.BooleanField(default=False)),
                ('tournament_stage', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='LocalTournamentsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(default=-1)),
                ('players', models.TextField(default='[]')),
                ('winner', models.CharField(max_length=8)),
                ('second', models.CharField(max_length=8)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
