# Generated by Django 4.2.7 on 2024-03-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localhistory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localmatcheshistory',
            name='tournament_stage',
            field=models.TextField(blank=True, default=''),
        ),
    ]
