# Generated by Django 4.2.7 on 2024-03-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GamesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('won_by', models.PositiveIntegerField()),
                ('lost_by', models.PositiveIntegerField()),
                ('player1_score', models.PositiveIntegerField()),
                ('player2_score', models.PositiveIntegerField()),
                ('tournament_game', models.BooleanField(default=False)),
                ('tournament_stage', models.TextField(default='')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.TextField(default='Tournament X')),
                ('game_type', models.TextField(default='tournament')),
                ('friends_only', models.BooleanField(default=False)),
                ('password', models.CharField(blank=True, default='', max_length=200)),
                ('score_to_win', models.PositiveSmallIntegerField(default=3)),
                ('max_partecipants', models.PositiveSmallIntegerField(default=8)),
                ('creator', models.BigIntegerField(default=-1)),
                ('status', models.TextField(default='pending')),
                ('players_id', models.TextField(default='[]')),
                ('placements', models.TextField(default='[]')),
                ('structure', models.TextField(default='')),
                ('is_active', models.BooleanField(default=True)),
                ('started', models.BooleanField(default=False)),
                ('end_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
