# Generated by Django 4.2.7 on 2024-03-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tx_hash',
            field=models.TextField(default=''),
        ),
    ]
