#!/bin/sh

max_attempts=10
delay_seconds=5
attempt=1

while [ $attempt -le $max_attempts ]; do
    # Attempt to curl the Vault server
    curl -vik https://vault:8200 && break

    # Increment the attempt counter
    ((attempt++))

    # Sleep for a short duration before the next attempt
    sleep $delay_seconds
done

#root_token=$(cat /app/backend/shared-volume/root_token.txt)
creds_token=$(cat /app/backend/shared-volume/credentials_token.txt)

response=$(curl -vik -H "X-Vault-Token: $creds_token" https://vault:8200/v1/cubbyhole/approle_role)
approle_role=$(echo "$response" | awk -F '"' '{print $18}' | tr -d '[:space:]')
export APPROLE_ROLE=$approle_role

#echo "second try"
#response2=$(curl -vik -H "X-Vault-Token: $root_token" https://vault:8200/v1/cubbyhole/approle_role)
#echo "CIAOOOOOOOOOOOO $(echo "$response2" | awk -F '"' '{print $18}' | tr -d '[:space:]')"

response=$(curl -vik -H "X-Vault-Token: $creds_token" https://vault:8200/v1/cubbyhole/approle_secret)
approle_secret=$(echo "$response" | awk -F '"' '{print $18}' | tr -d '[:space:]')
export APPROLE_SECRET=$approle_secret

#curl --header "X-Vault-Token: $root_token" --request DELETE https://vault:8200/v1/cubbyhole/approle_role
#curl --header "X-Vault-Token: $root_token" --request DELETE https://vault:8200/v1/cubbyhole/approle_secret
#unset root_token